prettier

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -92,8 +92,8 @@ jobs:
       - name: Run Extract Evals (textExtract)
         run: npm run evals category extract -- --extract-method=textExtract
         continue-on-error: true
-#      - name: Save Extract Text Results
-#        run: mv eval-summary.json eval-summary-extract-text.json
+      #      - name: Save Extract Text Results
+      #        run: mv eval-summary.json eval-summary-extract-text.json
 
       - name: Log and Compare Extract Evals Performance
         run: |
@@ -149,8 +149,8 @@ jobs:
       - name: Run text_extract Evals (textExtract)
         run: npm run evals category text_extract -- --extract-method=textExtract
         continue-on-error: true
-#      - name: Save text_extract Text Results
-#        run: mv eval-summary.json eval-summary-text_extract-text.json
+      #      - name: Save text_extract Text Results
+      #        run: mv eval-summary.json eval-summary-text_extract-text.json
 
       - name: Log and Compare text_extract Evals Performance
         run: |
@@ -159,16 +159,16 @@ jobs:
           echo "DomExtract text_extract category score: $dom_score%"
           echo "View domExtract results: https://www.braintrust.dev/app/Browserbase/p/stagehand/experiments/${experimentNameDom}"
 
-#          experimentNameText=$(jq -r '.experimentName' eval-summary-text_extract-text.json)
-#          text_score=$(jq '.categories.text_extract' eval-summary-text_extract-text.json)
-#          echo "TextExtract text_extract category score: $text_score%"
-#          echo "View textExtract results: https://www.braintrust.dev/app/Browserbase/p/stagehand/experiments/${experimentNameText}"
+  #          experimentNameText=$(jq -r '.experimentName' eval-summary-text_extract-text.json)
+  #          text_score=$(jq '.categories.text_extract' eval-summary-text_extract-text.json)
+  #          echo "TextExtract text_extract category score: $text_score%"
+  #          echo "View textExtract results: https://www.braintrust.dev/app/Browserbase/p/stagehand/experiments/${experimentNameText}"
 
-          # Fail CI only if textExtract is below 80%
-#          if (( $(echo "$text_score < 80" | bc -l) )); then
-#            echo "textExtract text_extract category score is below 80%. Failing CI."
-#            exit 1
-#          fi
+  # Fail CI only if textExtract is below 80%
+  #          if (( $(echo "$text_score < 80" | bc -l) )); then
+  #            echo "textExtract text_extract category score is below 80%. Failing CI."
+  #            exit 1
+  #          fi
 
   run-act-evals:
     runs-on: ubuntu-latest
